name: SSH to Linux Server

on:
  push:
    branches:
      - main

jobs:
  ssh_job:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH Command
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user "echo 'Hello from self-hosted runner!'"
