name: SSH to Linux Server

on:
  push:
    branches:
      - main

jobs:
  ssh_job:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: SSH Command
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'Hello from GitHub Actions!'"
