name: SSH
# 手動実行用のトリガー
on: [ workflow_dispatch ]
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: generate key
      run: |
        mkdir -p .ssh && chmod 700 .ssh
        echo "$SSH_KEY" > .ssh/id_rsa && chmod 600 .ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: ssh and command execution
      run: |
         ssh -t -t -o "StrictHostKeyChecking=no" -i .ssh/id_rsa $HOST "
         hostname
         "
      env:
        HOST: ${{ secrets.HOST }}